# .github/workflows/docker-release.yml
name: Build and Push Docker Image (Release)

on:
  release:
    types: [published]

jobs:
  build-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract release tag
        id: vars
        run: echo "release_tag=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT

      - name: Build and push release tags
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/fhir-ig-publisher:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/fhir-ig-publisher:${{ steps.vars.outputs.release_tag }}
